spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=resumebuilder_v2

# SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=727723eucs071@skcet.ac.in
spring.mail.password=muvrenjunoghsdxf

# SMTP properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Sender address used by EmailService
spring.mail.properties.mail.smtp.from=727723eucs071@skcet.ac.in

# App URL
app.base.url=http://localhost:8081