spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=resumebuilder_v2

# SMTP (Brevo / relay)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=abe4a4001@smtp-brevo.com
spring.mail.password=abe4a4001@smtp-brevo.com
